### PR TITLE
some fixes

### LINKED ISSUE #211: applogo rollover color
minor visual quirk: mousing over the top logo colors it gray, but mousing over the bottom one makes it blue.  These should probably match.

### LINKED ISSUE #212: tooltip relative dates
Put a tooltip on relative dates (an hour ago) to the absolute datetime (2016-08-01T12:00Z)

### LINKED ISSUE #225: Game mode and time ago should use subtext style

### PR DESCRIPTION
**Pull request by blukai**
fixes #211 
fixes #212 
fixes #225

### CODE REVIEW

**Comment by blukai** [comment]
If player_slot 0
image

File: src/components/Visualizations/TableHeroImage.jsx [hunk 1]
```diff
@@ -10,10 +10,10 @@ const TableHeroImage = ({ parsed, imageUrl, heroName, subText }) => (
       <div className={styles.parsed}>
         <div data-tip data-for="parsed">
           <ActionDoneAll color={styles.blue} className={styles.actionDoneAll} />
+          <ReactTooltip id="parsed" place="right" type="light" effect="solid">
+            Replay has been parsed for additional statistics
```
Comment (howardchung) [inline src/components/Visualizations/TableHeroImage.jsx]: externalize the string?

File: src/utility/index.jsx [hunk 2]
```diff
@@ -73,22 +75,46 @@ export function fromNow(input) {
...
-    return `${(diff / day).toFixed(0)} days ago`;
+    fromNow = `${(diff / day).toFixed(0)} days ago`;
   } else if (diff < (year * 2)) {
-    return `${(diff / month).toFixed(0)} months ago`;
+    fromNow = `${(diff / month).toFixed(0)} months ago`;
+  } else {
+    fromNow = `${(diff / year).toFixed(0)} years ago`;
+  }
+
+  if (tooltip) {
```
Comment (howardchung) [inline src/utility/index.jsx]: I think the string logic and the tooltip generation should be separated into different functions.

File: src/utility/index.jsx [hunk 3]
```diff
@@ -97,11 +123,11 @@ export const camelToSnake = str =>
   str.replace(/\.?([A-Z]+)/g, (match, group) => `_${group.toLowerCase()}`).replace(/^_/, '');
 
 const getSubtext = row => {
-  if (row.match_id && row.player_slot) {
+  if (row.match_id && (row.player_slot || row.player_slot === 0)) {
```
Comment (howardchung) [inline src/utility/index.jsx]: Just check row.player_slot !== undefined?

File: src/components/Visualizations/Table/KDA.jsx [hunk 4]
```diff
@@ -20,7 +20,7 @@ const KDA = ({ kills, deaths, assists, matchId = uuid.v4() }) => {
           <div style={{ width: `${(assists * 100) / kdaSum}%`, backgroundColor: palette.green }} />
         </div>
         <ReactTooltip id={`kda-${matchId}`} place="right" type="light" effect="float">
-          {`KDA: ${Number(((kills + assists) / (deaths + 1)).toFixed(2))}`}
+          {`${strings.abbr_kda}: ${Number(((kills + assists) / Math.max(deaths, 0)).toFixed(2))}`}
```
Comment (howardchung) [inline src/components/Visualizations/Table/KDA.jsx]: I prefer the old formula, since it doesn't have a discontinuity between 0 and 1.

File: src/utility/index.jsx [hunk 5]
```diff
@@ -96,22 +95,7 @@ export function fromNow(input, tooltip = false) {
...
-            date.toLocaleDateString('en-US', {
-              day: 'numeric',
-              month: 'short',
-              year: 'numeric',
-            })
-          }
-        </ReactTooltip>
-      </div>
-    );
+    return <FromNowTooltip fromNow={fromNow} date={date} />;
```
Comment (howardchung) [inline src/utility/index.jsx]: I was actually thinking:
* The fromNow(date) function should convert a date to a string.  This should a standalone utility function.
* The FromNowTooltip component should accept a date, and then have a reference to the fromNow() function in utility, which it uses to build the markup.

File: src/components/Visualizations/Table/KDA.jsx (hunk 4 above)
Comment (blukai) [inline src/components/Visualizations/Table/KDA.jsx]: but if player dies more than 0 times `kda` will be wrong
11 7 11 = 3.14
11 7+1 11 = 2.74

File: src/utility/index.jsx (hunk 5 above)
Comment (blukai) [inline src/utility/index.jsx]: ok, I will do it tomorrow

File: src/components/Visualizations/Table/KDA.jsx (hunk 4 above)
Comment (howardchung) [inline src/components/Visualizations/Table/KDA.jsx]: If we consider it as a "kills/assists to lives" ratio it makes more sense.

Comment (dartharaknus) [inline src/components/Visualizations/Table/KDA.jsx]: `Math.max(deaths, 1)` is a better representation.

File: src/components/Visualizations/FromNowTooltip.jsx [hunk 6]
```diff
@@ -1,18 +1,22 @@
...
 import ReactTooltip from 'react-tooltip';
 import uuid from 'node-uuid';
-
-export default ({
+import {
   fromNow,
-  date,
+} from 'utility';
+
+const FromNOwTooltip = ({
```
Comment (howardchung) [inline src/components/Visualizations/FromNowTooltip.jsx]: Casing on the O

File: src/components/Visualizations/Table/KDA.jsx [hunk 7]
```diff
@@ -20,7 +20,7 @@ const KDA = ({ kills, deaths, assists, matchId = uuid.v4() }) => {
           <div style={{ width: `${(assists * 100) / kdaSum}%`, backgroundColor: palette.green }} />
         </div>
         <ReactTooltip id={`kda-${matchId}`} place="right" type="light" effect="float">
-          {`${strings.abbr_kda}: ${Number(((kills + assists) / Math.max(deaths, 0)).toFixed(2))}`}
+          {`${strings.abbr_kda}: ${Number(((kills + assists) / Math.max(deaths, 1)).toFixed(2))}`}
```
Comment (howardchung) [inline src/components/Visualizations/Table/KDA.jsx]: I'm fine with this, but note that it will not match the server-side KDA (for records, etc.) since we compute it differently there.

**Comment by howardchung** [comment]
LGTM, ready to merge?

**Comment by blukai** [comment]
@howardchung, yes

File: src/components/Visualizations/Table/KDA.jsx (hunk 7 above)
Comment (dartharaknus) [inline src/components/Visualizations/Table/KDA.jsx]: We need to change them too.

Comment (dartharaknus) [inline src/components/Visualizations/Table/KDA.jsx]: I have always had an issue with KDA in opendota.

Comment (howardchung) [inline src/components/Visualizations/Table/KDA.jsx]: We can update the code to compute future values, but back-computing the old data will be very expensive.
