### PR TITLE
Iss-782

### LINKED ISSUE #782: Summary component layout issue if no matches
@blukai 

If the player has no matches, the layout of match overview gets weird:
http://hchung.westus.cloudapp.azure.com:8080/players/139696462

(There was also a crash issue but I hotfixed that)

### PR DESCRIPTION
**Pull request by blukai**
fixes #782

### CODE REVIEW

File: src/components/Player/Pages/Overview/Summary.jsx [hunk 1]
```diff
@@ -90,13 +90,15 @@ const SummOfRecMatches = ({ matchesData }) => {
...
-          <span>{strings.th_winrate}</span>
-          <p>{winrate}%</p>
-        </li>
-        {Object.keys(computed).map((key) => {
+        {winrate
+          ? <li>
+            <span>{strings.th_winrate}</span>
+            <p>{winrate}%</p>
+          </li>
+          : ''
```
Comment (masad-frost) [inline src/components/Player/Pages/Overview/Summary.jsx]: Prefer null, empty strings create a stupid <span>. Apparently this will be fixed in react fiber.
