### PR TITLE
Axis fix

### LINKED ISSUE #459: Number rounding issue in graph y-axis
From reddit:

1: https://www.opendota.com/players/349232998/trends/purchase_tpscroll Not all values on Y axis are not rounded

2: lasthits on objectives made by player's illusions are attributed to them on overview/buildings map, but are attributed to Anonymous on log pages

https://www.opendota.com/matches/2766655835/overview If you look at buildings map, radiant top barracks, Morphling got last hit on both of them However, since it was done by illusions, rax are attributed to Anonymous on the log page (https://www.opendota.com/matches/2766655835/log 44:44 44:48) Same thing for Naga's illusions and bottom ranged rax

### LINKED ISSUE #581: MMR History Graph not loading
- **OS**: Windows 10
- **Screen Resolution**: 1366x768
- **Browser/Version**: Chrome / Microsoft Edge
- **Link to page with the issue, or screenshot**: http://i.imgur.com/xm1x9mZ.png

MMR Graph is not loading for me. I have addblock off. I tried using incognito mode on Chrome and Microsoft Edge but it is not loading. The loading animation is playing for a couple of seconds and then freezes. I asked someone else and told me it is loading for them. I also tried using mobile data to load the site but still not working. Other categories work fine.

### PR DESCRIPTION
**Pull request by howardchung**
fixes #459 
fixes #581 

* remove usage of color dependency
* added hsvtorgb converter function
* Format axis values to avoid weird roundoff errors

### CODE REVIEW

File: src/components/Visualizations/Graph/HistogramGraph.jsx [hunk 1]
```diff
@@ -1,20 +1,58 @@
...
+ * adapted from http://en.wikipedia.org/wiki/HSV_color_space.
+ * Assumes h, s, and v are contained in the set [0, 1] and
+ * returns r, g, and b in the set [0, 255].
+ *
+ * @param   Number  h       The hue
+ * @param   Number  s       The saturation
+ * @param   Number  v       The value
+ * @return  Array           The RGB representation
+ */
+function hsvToRgb(h, s, v) {
```
Comment (mike-robertson) [inline src/components/Visualizations/Graph/HistogramGraph.jsx]: Can we move this to utility/index
