### PR TITLE
Fix slow searchbar

### LINKED ISSUE #745: Search bar is really slow when on a player or match page
Typing is so janky, probably a performance issue

### PR DESCRIPTION
**Pull request by masad-frost**
fixes #745

Only triggers pro player search when on search page and it's debounced to make it completely smooth.

### CODE REVIEW

File: src/components/Search/SearchForm.jsx [hunk 1]
```diff
@@ -1,53 +1,84 @@
...
+  constructor(props) {
+    super(props);
+
+    let query = '';
+    const location = browserHistory.getCurrentLocation();
+    if (location.pathname === '/search') {
+      // Avoid getting ?q= from other paths
+      query = location.query.q;
+    }
+    this.state = { query };
```
Comment (masad-frost) [inline src/components/Search/SearchForm.jsx]: FYI, I couldn't get it from the store because it seems like it updates after the search component mounts. Doing it in componentWillReceiveProps might cause some race conditions.

File: src/components/Search/SearchForm.jsx [hunk 2]
```diff
@@ -1,53 +1,84 @@
 import React from 'react';
 import { connect } from 'react-redux';
 import { browserHistory } from 'react-router';
+import { debounce } from 'lodash';
```
Comment (howardchung) [inline src/components/Search/SearchForm.jsx]: If debounce isn't too hard to implement without using lodash, I'd like to at some point remove our dependency on lodash at some point to reduce bundle size.

Comment (masad-frost) [inline src/components/Search/SearchForm.jsx]: We can use 'lodash.debounce' from npm

Comment (masad-frost) [inline src/components/Search/SearchForm.jsx]: Or do https://lodash.com/custom-builds if you want
