### PR TITLE
distrib/rankings fixes

### LINKED ISSUE #257: Distributions fixes
- [x] port over data bias warning
- [x] show number of players in solo mmr distribution
- [x] add rank number to each country

### PR DESCRIPTION
**Pull request by howardchung**
fixes #257 

* Use standard Table element
* Use standard spinner element
* Externalize some strings

Could use some more styling on the distributions warning/number of players display.

Reviewers:
@bguzryanto 
@nicholashh 
@albertcui

### CODE REVIEW

File: src/components/Heroes/Ranking.jsx [hunk 1]
```diff
@@ -47,7 +39,7 @@ class Ranking extends Component {
     return (
       <div>
         {isLoading || isError || rankings === null ?
-          renderLoading() : renderRanking(hero, rankings)}
+          <Spinner /> : renderRanking(hero, rankings)}
```
Comment (mike-robertson) [inline src/components/Heroes/Ranking.jsx]: Should we show a spinner if there is an error or rankings === null? Should we instead show some sort of error message or nothing?

File: src/components/Heroes/Benchmark.jsx [hunk 2]
```diff
@@ -48,7 +39,7 @@ class Benchmark extends Component {
     return (
       <div>
         {isLoading || isError || result === null ?
-          renderLoading() : renderBenchmark(hero, result)}
+          <Spinner /> : renderBenchmark(hero, result)}
```
Comment (mike-robertson) [inline src/components/Heroes/Benchmark.jsx]: same comment as below

File: src/components/Distributions/Distributions.jsx [hunk 3]
```diff
@@ -14,31 +13,58 @@ import {
...
+    <Tabs>
+      {Object.keys(data).map(key => (
+        <Tab key={key} label={strings[`distributions_${key}`]}>
+          <Heading title={strings[`distributions_${key}`]} />
+          {(key === 'mmr') ?
+            <div>
+              <div>{`${data
+              && data.mmr
+              && data.mmr.rows
+              && data.mmr.rows.map(row => row.count).reduce(sum)} ${strings.th_players}`}</div>
```
Comment (mike-robertson) [inline src/components/Distributions/Distributions.jsx]: spacing here is a little confusing
