### PR TITLE
scrolling fixes for mobile

### LINKED ISSUE #312: Certain match pages don't scroll tables properly in mobile

### PR DESCRIPTION
**Pull request by howardchung**
fixes #312 

I identified that using react-flexbox-grid on match table components was breaking the scrolling on mobile.  I adapted some of the ideas from #313 to solve this.

Also rearranged damage inflictors to save some space

Reviewers:
@mike-robertson 
@blukai

### CODE REVIEW

File: src/components/Match/matchPages.jsx [hunk 1]
```diff
@@ -129,46 +128,42 @@ const matchPages = [{
...
-    <Col md={6}>
-      <Heading title={strings.heading_damage} />
-      <CrossTable match={match} field1="damage" field2="damage_taken" />
-    </Col>
-    <Col md={12}>
-      <TeamTable match={match} columns={inflictorsColumns} heading={strings.heading_damage} />
-    </Col>
-  </Row>),
+  content: match => (<div>
+    <div style={{ display: 'flex', flexWrap: 'wrap', overflow: 'auto' }}>
```
Comment (blukai) [inline src/components/Match/matchPages.jsx]: Put styles in css file?

**Comment by howardchung** [comment]
re-review?
